---
- name: Provision and Configure EC2 Instance for Flask Web App
  hosts: n3
  become: true
  vars:
    flask_app_dir: "/var/www/flaskapp"
    flask_app_file: "app.py"
    flask_app_service: "flaskapp"
  tasks:
    - name: Update package cache and install required packages
      yum:
        name:
          - python3
          - python3-pip
          - python3-devel
          - gcc
          - nginx
        state: present

    - name: Configure firewall to allow HTTP traffic
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Clone Flask web app code from GitHub
      git:
        repo: git@github.com:all4cliff/Flask-web-app.git
        dest: "{{ flask_app_dir }}"
        clone: yes

    - name: Install Flask and other required Python packages
      pip:
        name:
          - flask
          - uwsgi
        executable: /usr/bin/pip3

    - name: Configure uWSGI for Flask web app
      copy:
        content: |
          [uwsgi]
          module = {{ flask_app_file.split('.')[0] }}
          callable = app
          master = true
          processes = 5
          socket = /tmp/{{ flask_app_file.split('.')[0] }}.sock
          chmod-socket = 666
          vacuum = true
        dest: "{{ flask_app_dir }}/{{ flask_app_file.split('.')[0] }}.ini"
        mode: 0644

    - name: Configure systemd service for Flask web app
      copy:
        content: |
          [Unit]
          Description=uWSGI instance to serve {{ flask_app_file }}
          After=network.target

          [Service]
          User=root
          Group=root
          WorkingDirectory={{ flask_app_dir }}
          Environment="PATH=/usr/bin"
          ExecStart=/usr/bin/uwsgi --ini {{ flask_app_file.split('.')[0] }}.ini

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/{{ flask_app_service }}.service"
        mode: 0644

    - name: Start and enable systemd service for Flask web app
      systemd:
        name: "{{ flask_app_service }}"
        state: started
        enabled: yes

...