---
- name: Provision and configure EC2 instance for Flask web app
  hosts: n3
  become: true
  vars:
    flask_app_port: 5000

  tasks:
    - name: Install Python 3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install required Python packages
      pip:
        name:
          - flask
          - gunicorn
        state: present

    - name: Configure firewall to allow incoming traffic on port 80 and 5000
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items:
        - 80
        - "{{ flask_app_port }}"

    - name: Clone Flask web app from GitHub
      git:
        repo: https://github.com/your-github-repo/flask-app.git
        dest: /opt/flask-app

    - name: Start Flask web app as a service
      systemd:
        name: flask-app.service
        enabled: true
        state: started
        daemon_reload: true
        template: |
          [Unit]
          Description=Flask web app
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/opt/flask-app
          ExecStart=/usr/bin/gunicorn --bind 0.0.0.0:{{ flask_app_port }} wsgi:app
          Restart=always

          [Install]
          WantedBy=multi-user.target
        
...